### ISSUE TITLE
is this based in the latest UIKIT version??? are server render compatible??

### ISSUE THREAD

**Issue by cocodrino** [vuikit/vuikit#120]
Hi guys, would be great if you can include in the README.md which uikit version are you using, not sure but I can't see flex component here https://vuikit.js.org/#/ ...so I assume it's not using the latest uikit version no???

also would be great if you include which components are SSR compatible...thank you guys...

**Comment by miljan-aleksic** [comment]
Hi, it's based on Vue 2 and UIkit 3, readme updated :)

The flex component is more of a CSS style helper than a component, as such simply use it as indicated in the UIkit documentation. Anyhow, porting those docs in the Vuikit ones could be helpful.

The entire library is compatbile with SSR, at least it should not brake it rendering.

**Comment by cocodrino** [comment]
thank you @miljan-aleksic now it's much more clear to me...I going to test it and check...

another question: uikit allows you change the theme just changing your scss variables...

```css
$global-link-color: #DA7D02;

// 2. Import default variables and available mixins.
@import "uikit/src/scss/variables-theme.scss";
@import "uikit/src/scss/mixins-theme.scss";

// 3. Your custom mixin overwrites.
@mixin hook-card() { color: #000; }

// 4. Import UIkit.
@import "uikit/src/scss/uikit-theme.scss";
```

with vuikit how must I edit these variables???...I'm using nuxt, thank you
