### ISSUE TITLE
Off-canvas example does not seem to work

### ISSUE THREAD

**Issue by kkinder** [vuikit/vuikit#55]
1.  Go to the [codepin](http://codepen.io/miljan/pen/YWXVKj) playground for vuikit.

2. Paste in the [example for off-canvas](https://vuikit.js.org/#/offcanvas):

```
<vk-button @click.native="show = true">
  Show
</vk-button>
<vk-offcanvas :show="show"
  @clickOut="show = false">
  Content
</vk-offcanvas>
```

As you can tell, it doesn't seem to work.

Similarly, I'm seeing that it's not working inside my app. The classes are changing, but it isn't showing the off-canvas. Very strange.

**Comment by miljan-aleksic** [comment]
@kkinder, you are right. Some of the components require adapting the CSS rules to work properly and the playground was using the default UIkit theme. I have update it now to use Vuikit theme and seems working fine. For custom themes please review the README.

**Comment by kkinder** [comment]
Hmm, on my project, I am using the extra less styles from the readme. Do I need to use the whole theme?

**Comment by miljan-aleksic** [comment]
No, just apply those rules to your custom theme.

**Comment by miljan-aleksic** [comment]
Show me your theme less code.

**Comment by kkinder** [comment]
Thanks for your help. I can probably put together a working demo of the issue if that would be easier, but here's the less code, direct from my app.vue. (uikit/src is directly from uikit itself):

```
<style lang="less">
@import "~uikit/src/less/uikit.less";

.hook-modal() {
  // reset hardcoded transitions
  display: inherit;
  opacity: inherit;
  -webkit-transform: inherit;
  transform: inherit;

  // add custom ones
  -webkit-transition: opacity .3s ease;
  transition: opacity .3s ease;
}

.hook-modal-dialog() {
  // reset hardcoded transitions
  opacity: inherit;
  -webkit-transform: inherit;
  transform: inherit;

  // add custom ones
  -webkit-transition: all .3s ease;
  transition: all .3s ease;
}

// add custom transitions
.hook-modal-misc() {
  .vk-modal-transition-enter .uk-modal-dialog {
    opacity: 0;
  }
  .vk-modal-transition-leave-active .uk-modal-dialog {
    opacity: 0;
  }
  .vk-modal-transition-enter .uk-modal-dialog,
  .vk-modal-transition-leave-active .uk-modal-dialog {
    -webkit-transform: scale(1.1);
    transform: scale(1.1);
  }
}
    // reset hardcoded transitions
    .hook-dropdown-misc() {
      .uk-dropdown,
      .uk-dropdown-blank {
        display: inherit;
      }
    }
</style>

```

**Comment by miljan-aleksic** [comment]
@kkinder, actually OffCanvas doesn't need any additional rules. Only Modal, Dropdown and Table.

But could be that you are not importing the OffCanvas styles at all in your theme? Check your main uikit.less and let me know. If the issue persist, yes, please, recreate this in a working demo.

**Comment by kkinder** [comment]
uikit.less does indeed pull in off-canvas styles. In fact, I can see them in my debugger. The problem seems to be that vuikit isn't reading the width of the off-canvas element correctly?

Without pulling my whole repo in, [here's a reproduction](http://codepen.io/anon/pen/BpyYXd) in Codepin. It's not identical to what I'm using, but the outcome seems to be the same.

**Comment by miljan-aleksic** [comment]
Sorry, you are right... Please add the following to your custom theme.

```less
.hook-offcanvas() {
  // null hardcoded transitions
  display: inherit;
  // necessary for Vue transition hooks
  transition-duration: @offcanvas-transition-speed;
}
.hook-offcanvas-bar() {
  // apply new transitions
  -webkit-transform: translateX(-100%);
  -ms-transform: translateX(-100%);
  transform: translateX(-100%);
  transition: transform @offcanvas-transition-speed @offcanvas-transition-timing;
}
.hook-offcanvas-misc() {
  .uk-offcanvas-page {
    transition: margin-left @offcanvas-transition-speed @offcanvas-transition-timing;
  }
  .uk-offcanvas-page-open .uk-offcanvas-bar,
  .uk-offcanvas-page-open .uk-offcanvas-bar {
    -webkit-transform: translateX(0%);
    -ms-transform: translateX(0%); // IE9
    transform: translateX(0%);
  }
}
```
